apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    component: mongodb
    project: roboshop
    env: dev 
    tier: database 
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongodb
      project: roboshop
      env: dev 
      tier: database

  template:
    metadata:
      labels:
        component: mongodb
        project: roboshop
        env: dev 
        tier: database
    spec:
      containers:
        - name: mongodb
          image: shanmukhatadisetti/mongodb:v1
        
